name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: pdfs
          build_html: false
      - name: Combine PDFs
        id: combine
        uses: elMuso/MergePDFs-action@1.1
        with:
          path: pdfs
          filename: Trestman-Job-Application-Materials
      - uses: actions/upload-artifact@v1
        with:
          name: Trestman-Job-Application-Materials
          path: pdfs/Trestman-Job-Application-Materials.pdf
